### ISSUE TITLE
Unable to flash the dds-238-2

### ISSUE THREAD

**Issue by Brackbouille** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#14]
Dear all

This is not the first product that i flash with tasmota, but for this one impossible.
I could pair with smartlife without issue, so it means this is not an issue with hardware.

I have soulded connector to RX TX VCC and GPI00, put GPI00 on ground when starting (used tasmotizer) but it not works.

has anyone had the same problem ? or an idea ?

Thanks in advance

**Comment by krikk** [comment]
did you have a look at this: https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/issues/13

...but are you sure that the hardware is still the same, because smartlife app works also with non-tasmota compatible hardware...

does the chip still look like this: https://raw.githubusercontent.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/main/pictures/displayboard_back_with_espboard.jpg ?

**Comment by g6094199** [comment]
> 

you can leave GPIO0 grounded for the whole process. worked for me flawlessly. 
in general i flash with ESPTool but it should make no difference.
