### ISSUE TITLE
How to get the exact value of the Counter at the exact Number of Wh ??

### ISSUE THREAD

**Issue by seby90** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#29]
Hello, I just flashed tasmota on my dds238-2. 
Everything works well except for an inaccurate count. Indeed, the value of the counter that we receive "TuyaReceived#DpType2Id101" must be multiplied by 10 to obtain a value in Wh. 
For the record, a flashing LED = 1 Wh. 
The incrementation of the counter received by the variable TuyaReceived#DpType2Id101 is done every 10 Wh ...  There would be no other way to get the exact value of the meter at the exact number of Wh??
Besides, I can't understand how tasmota can give us a consumption value of 1 Wh?? 
If anyone has an idea...

**Comment by krikk** [comment]
> For the record, a flashing LED = 1 Wh.

no, mine says: 
![image](https://user-images.githubusercontent.com/5165445/229118708-184fefde-565f-41b1-ac08-78c835a44013.png)
which i would understand as: 1600 led flashes = 1000 Wh

...and i do not understand your question, i get a value of:
![image](https://user-images.githubusercontent.com/5165445/229119347-b8800d22-4306-47d9-8246-1188af4aa88a.png)
...and this value matches the displayed value and seems valid for me...

**Comment by krikk** [comment]
if both curves show the same data:

the first curve is better because it has more accuracy... the second curve is more "smooth" because it shows averaged values (because of the 5 minutes intervall)

...i think you should "rethink" your data...

here a graph of my data:
![image](https://user-images.githubusercontent.com/5165445/229148077-07ca28e0-01ac-4192-a662-450563fe6447.png)
"PV Power" = Hiking-DDS238-2-WIFI
"APS YC60" = power reported by my inverter

**Comment by krikk** [comment]
yep, you are right, we only get the total power value with 10Wh accuracy... but this is all we get from the "tuya" chip... you see the raw data on the console... so to get more accurate data you problable have to calculate it manually, out of the current power values... could possibly implemented with a tasmota rule, feel free to reopen and post your solution here if you find a good one...
